/** Cross-language contract tests: decode the golden fixtures generated by
 *  bridge/tests/gen_fixtures.py and assert against expected.json. */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { decode } from '@msgpack/msgpack'
import { encodeCommand, toAlignedFloat32 } from './protocol'

const FIXTURES = join(__dirname, '../../../../bridge/tests/fixtures')

interface ExpectedFrame {
  topic: string
  ts: number
  seq: number
  data?: Record<string, unknown>
  points?: number[][]
}

const expected = JSON.parse(
  readFileSync(join(FIXTURES, 'expected.json'), 'utf-8'),
) as Record<string, ExpectedFrame & { command?: Record<string, unknown> }>

function decodeFixture(name: string) {
  return decode(readFileSync(join(FIXTURES, name))) as {
    topic: string
    ts: number
    seq: number
    data: unknown
  }
}

describe('golden fixtures (Python -> TS contract)', () => {
  for (const name of ['hello.bin', 'pose.bin', 'stats.bin', 'log.bin']) {
    it(`decodes ${name}`, () => {
      const frame = decodeFixture(name)
      const exp = expected[name]
      expect(frame.topic).toBe(exp.topic)
      expect(frame.ts).toBe(exp.ts)
      expect(frame.seq).toBe(exp.seq)
      expect(frame.data).toEqual(exp.data)
    })
  }

  it('decodes scan_4pts.bin into aligned float32 points', () => {
    const frame = decodeFixture('scan_4pts.bin')
    const exp = expected['scan_4pts.bin']
    expect(frame.topic).toBe('scan')
    const view = frame.data as Uint8Array
    expect(view).toBeInstanceOf(Uint8Array)
    expect(view.byteLength % 16).toBe(0)
    const points = toAlignedFloat32(view)
    expect(points.byteOffset).toBe(0) // aligned: starts at its own buffer
    expect(Array.from(points)).toEqual(exp.points!.flat())
  })

  it('encodes set_param identically to the Python fixture', () => {
    // Python generated cmd_set_param.bin from the same logical command —
    // decode both and compare structurally (map key order may differ).
    const fromPython = decode(readFileSync(join(FIXTURES, 'cmd_set_param.bin')))
    const ours = decode(
      encodeCommand({ cmd: 'set_param', id: 8, node: 'slam', params: { voxel_size: 0.1 } }),
    )
    expect(ours).toEqual(fromPython)
    expect(fromPython).toEqual(expected['cmd_set_param.bin'].command)
  })
})

describe('toAlignedFloat32', () => {
  it('handles views at unaligned byte offsets', () => {
    const floats = new Float32Array([1.5, -2.5, 3.25])
    const raw = new Uint8Array(floats.buffer)
    // place at offset 1 inside a larger buffer to force misalignment
    const padded = new Uint8Array(raw.byteLength + 1)
    padded.set(raw, 1)
    const view = new Uint8Array(padded.buffer, 1, raw.byteLength)
    expect(view.byteOffset % 4).not.toBe(0)
    expect(Array.from(toAlignedFloat32(view))).toEqual([1.5, -2.5, 3.25])
  })
})
